---
origin: "vessels.urn:mrn:imo:mmsi:244770688"
database:
  url: "postgres://gosk:gosk@localhost:5432/gosk2sslmode=disable"
mqtt: 
  username: "unknown"
  password: "unknown"
  url: "mqtt://broker.mqtt.cool:1883"
