---
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - builds:
      - "gosk"
    license: "Apache 2.0"
    formats:
      - "apk"
    dependencies:
      - "postgresql"
      - "postgresql-timescaledb-tsl"
    bindir: "/usr/bin"
