---
context: "vessels.urn:mrn:imo:mmsi:123456789"
protocol: "signalk"
mappings:
  - expression: "environment_outside_temperature - 200"
    path: "environment.inside.temperature"
    sourcePaths: 
      - "environment.outside.temperature"
