---
context: "vessels.urn:mrn:imo:mmsi:123456789"
protocol: "csv"
separator: ";"
splitLines: true
mappings:
  - expression: "floatValues[1]"
    path: "propulsion.mainEngine.drive.power"
    beginsWith: "TANK:CT-1"
